[package]
name = "json_schema_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonschema = "0.28.1"
schemars = "0.8.21"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
