name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install mise
        uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: Run mise lint
        run: mise lint
